spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/urlshortener
    username: postgres
    password: postgres

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  task:
    scheduling:
      enabled: true
      pool:
        size: 2

server:
  port: 8080

rate-limit:
  shorten:
    max-requests: 3
    window-seconds: 60
  redirect:
    max-requests: 3
    window-seconds: 60